### ISSUE TITLE
There's no firmware to flash keyboasrd?

### ISSUE THREAD

**Issue by doubleheiker** [dcpedit/dissatisfaction30#1]
hello bro, I'm interested about this 30, but I can't find any firmware of this keyboard, is there something I missing? looking forward your rely

**Comment by doubleheiker** [comment]
I got it, is it need I copy KLE raw data to Keyboard firmware builder to gen firmware?

**Comment by dcpedit** [comment]
Thank you for bringing that to my attention.  I totally forgot to add the firmware.  I've updated the repo with a `firmware` directory which contains the hex and a link to my firmware source.

**Comment by doubleheiker** [comment]
THX a lot! And during this afternoon I used your KLE raw data to generate a qmk firmware and via json file, learned a lot! hahaha
