### ISSUE TITLE
Which microcontroller should be used? 

### ISSUE THREAD

**Issue by t2ac32** [dcpedit/dissatisfaction30#3]
Sorry I’m barely new in all this keyboard hobby. 

I was wondering which microcontroller is shown being used in the photos and recommended to use for the PCB file. 

Thanks in advanced

**Comment by DrBomer** [comment]
pro micro with 32U4

**Comment by dcpedit** [comment]
Any controller with a pro-micro compatible footprint will work, but my case was designed for an Elite-C since it can be soldered directly to the PCB.  An Elite-Pi could theoretically work as well, but I haven't tried it
